[tool.poetry]
name = "salt2type"
version = "0.2.0"
description = "Saltarelle to TypeScript Migration Tool"
authors = ["Pangaea Information Technologies, Ltd."]
readme = "README.md"
repository = "https://github.com/pangaeatech/salt2type"
package-mode = false

[tool.black]
line-length = 150
target-version = ['py38']
include = 'salt2type|\.pyi?$'

[tool.poetry.dependencies]
black = "25.9.0"
coverage = "7.7.0"
dill = "0.4.0"
pdoc = "15.0.2"
pylint = "3.3.5"
python = "~3.13"
tomli = "2.2.1"
typing-extensions = "4.12.2"
