name: Automatically Create PR on New Branches
concurrency: auto-pr-${{ github.ref }}
on:
  push:
    branches-ignore:
      - "main"
      - "dependabot/**"
      - "renovate/**"
      - "whitesource/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: gh pr view || gh pr create -d -B "main" -t "${{ github.ref_name }}" -b ""
        env:
          GH_TOKEN: ${{ github.token }}
