name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
        lfs: true
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'

    - run: pip install -r requirements.txt

    - run: black --check -l 150 -t py38 salt2type

    - run: pylint salt2type
